apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:kwhqIJvntg7MX/wg/4Ilhina6kMjPvriVUOdAA5y6uj1Fzs4HD/N65JihnX6Y0FCP5HTxtcSxY2ffpWwm2FEN13k8PurnDy58PnxC7SqqJxnY6ylHzm0IkaxaIRrEfPkr7q2umGwCzx+QMJ4EFb3iQJsHc6jHNAqssqkEMbJ1HKRA0hjrwxM/So0LG/2dBQXJcdkDSyrUAXeAqhsNXNztoEV4HWwqzEU7CBaEQZg7vzrW7mOMK1spqmBEtQuhyzsrP/fJAZj0Cu1mZ7p2qcdDsnGDWygX4LMnN1rIO3OOqz+DMJXToGqGiWH7Sc6hmJiGFnb/Tvv/IXpXylCS8FNNDN7Yzi0QNsnkryPL5r5+QDO4OyHbQYl7QPJdKQZAEzeBB/PFhzoML3KACwendC5EGxw7u0SI9+L6eCbAKbot2+RTwlHUj93XF81RwH/xBkPr/PnUQcHd+4g58ppfUWYeHdUkkJLk036f+H967lSZ6a/xPqWHB6yNvfRXw6QzE84+RCzfBE9,iv:TxhPQeeFwUN3WtwG2+BrqXHJ61c6a9rda8BMywW4nys=,tag:VPmohi6iNR6LJC8X5VSe3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-14T03:43:54Z'
    mac: ENC[AES256_GCM,data:yErcK80L90p4WsOLdOIKMoLp8I+Yydmz9vfWbgg9CoGek0ywiIJ3WgJHwxUKattcDBn5VsTIQX9RfPfoaRRl+S3SG+ykge9nzxWV0LzWVbTSViYf793meQce8w+KPOqn3H1v9hxU1UchwZBb6WfaTUbBLCFkaSSpetmA9vG5B54=,iv:/lLPYiQOyfUbJLwS4r+CZVLzLnN0aE0/DXi2BjWxWRM=,tag:DF9KVqKcAaC/GZWRvJF3WQ==,type:str]
    pgp:
    -   created_at: '2020-11-17T04:12:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA93W3Fi3CqSYARAAkxXH58DZwkKS++G0k6meSbJJqj/Ai1vh7W2jP17KTHbl
            I2sPuTv9PfrorBoWMKz8witmnjHy7QKspxwl5+YWgwFZ0ESIwt/ArKhYqwyPGilz
            MLZ4cbsYyQZIHlnvoZYFeSJ0Blx1CmwG6LxTDjw0hupM38/p6U5Dkmuohq09GGJW
            JskA3ROKxAbXmw+vOm/qihDw3WgCQ02EShQpSzXoUzIklPgjHOxkCyVxHoOajba2
            WuueDbomOBan0vdfQFaLKhdPLSDfXf2KBnyEAqPWQ2zvF8T3nR8RFUvPtdg2FmO8
            H/+xF3//Jo4iTh1DjdRVpMdlM8qyhXdS1GpF86p6Ki6vjq2+eltnIPzIIg0KWlNp
            5qKGsOjr1m02x43pVLm537VFZrKJDobHZSsxVmtDk/TdyEa70FcQ2VlHX4k6mA9j
            KgxLJi++qKNx1nf+9ok1EzR4rN1pA7TjL2edLxFSiXHmfGl0oPz7PY/3pEG1q7qz
            ZWVJ3IAxxoq38jkqrtvlpOQGkv7isNAMbTWh45mSGeHUEPw7UzdssTwKh78r1V1E
            qarUuFxx6JlZCkPB/dJCnxot80CSuP9hc5eyvwveFP2KnKZi2Pst4nGmR4xKNCdd
            EwlmjI0WMXqSVmNlxK6EAWr3EvbMH5WrUeaQxrqvOHQfCPWH+pkJY1RGe1mHXFLS
            XgH4OwwYNd0kwxDKcJFhYl2QTWHwjoG8+Bo3nkR/W39+tyV/O0AzqlBm89c1+WJn
            VMUBiGmTXrl6GJfpHz3daAXOUAks8eGgXCGTd/xtdrbgtpZBOe6bAbJ9kDOBJno=
            =G/FT
            -----END PGP MESSAGE-----
        fp: DF9CA5B39E594B981080DE23F76E07FD8A05CF32
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
