apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:n95pXQqyLx/ArlH1p8cWhnP5RkCzLHX//jIZ11MTjGqp38sHt00merV6R6mHem5Xroa1CK3l4p2ueLnGAdBdfunWGbZGnYqLMTK0H9Oc2BGcATh51M0FC28mEXeTvhPpBxdiklZ3z6pscJ95LBBzX1U0yUYX1NAK7zxZajEBFBREsYhh/6AWmqnms8+7k/HoEt/fRYzGBNz9Elp6WzBBz8prVINpGHPAdTCT0rT1Px2JdRSjxk1t/YMRYYnb9IicwjN+V6IdjT53V+Ezs4LcO3OKkFTApqDL73zVslYAsl0PyGe+fQPphAaZa+/U2sn8iD8YQ+JyLzOC7sEbOVaUzCBXUEUvkPUhg04OZ5OdKbHvY72DmIPgb8lFWi7Zm5eS4Agy9QIdQnWprAzkd3wgOmAmlq9oUyP15n2DeT10aRLEJyzlWY1XgxinhrjBp0C17nj79k08NL34oqZoAlW9EJU0T6Qw1HLyYXwTanyHb+6ATv9rUD9YgCku8myh828/go/qmnsY,iv:3i9rH5Q4U6iRc5g9fIPNL64O7HHTzXKmkSG3znlM5gA=,tag:Hs+MMHElpmou6xVkbTuwOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-14T02:23:26Z'
    mac: ENC[AES256_GCM,data:mXo7QnkmvFdYn5t5WakhaKRv5tZ9XUHGJhkhKuNVX+zuxVzTPdIjns+ejBJYYiKe64y9cKtNUpKMuCf5VocxLS6ZHK4TYOsJ5YMspbz/6I+dvVhYxGiB4CFn/cX7YmlqLNAkxghRnS+NEL62Hg8Ogcpwjdh9Wb9s4MJkww09wTY=,iv:jqnigr98qrB7lRRcVjJa2CF+btV3N8kl2A0pUmgdtoU=,tag:oeFKudfc1Q/xidyL0tSV+w==,type:str]
    pgp:
    -   created_at: '2021-02-14T02:19:28Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwpvQwwKj+ndARAAiK/MISxAYg/++jBq2KXPfo5wLmYE3TWpYHwQqXnreLGg
            XL+ZgGJ3rww7AERxtoe1Zqb9VAJkkDlvZQHI3LStN1KKJf1cNSRBqj4fMmsPOp0Y
            FAN3nnAEdsqts1DmAEUNBZSitjS480vErzd2PwSKjDn5mlP7tbilA3uHIRZHzCM9
            JJtR+hXB/M9CpG7MVmupZG5Il97pzBWM2ter+HfGbeNmwXurC3Ga4+xntZ0MAzTb
            IjeA7mVTnMTFEmk9971pjxTu11zNoK/YBhiAfaWMxOYdF4qO6YHZwbpBOj9z6r6y
            futlxiWwVYrMcVr8zvckO3QZAkNrv3Gognc2kEjEoJ14JvvenWQegs4ObiQmjaEi
            BsvUO0qk8NSgAotIhaVmDBqg6InOvuDoTrgHf0VP5pNvT73FVJpR2WjCjn8MkRCS
            peYxnMmYV3vclcbS9SYAaMopWeu3x8FGdyaC/ANFm0rlXfRq90V8QEsafgpvsVcK
            VICiC6CPH2688tG20jnFYEWduNOo+U3naigiXExBncLVpz+UCRQj68vxmr1MnnzJ
            e3rO38cVTR6PGfvVenY6UcHWNHRP2G+waTwq24WDviERgmuG/LnHPkVOQ3i3/qpN
            drK3zfD4nei+VGbrlP54C54oaayenIrdwKiNWGJ5K10ppd0/wgH3YkmDM5rw86rS
            XgHBIgdr+rtPYGsiuTWQFswVfWlvHA3d70oR3BSMcLYxxkXcW+Ew+fpGPEc79WFu
            4X0HJH+PhFqhLoo1WsK6BgeBR/PkjJ5HezpQmxxHfEDufJPQBSOR7b4IuxbAYsQ=
            =S3Hh
            -----END PGP MESSAGE-----
        fp: DF9CA5B39E594B981080DE23F76E07FD8A05CF32
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
